# Generated by Django 5.2.17 on 2026-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='Support Vector Machine', max_length=100)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
